### ISSUE TITLE
[DESIGN] 상황 추가 뷰 UI 추가 구현

### ISSUE THREAD

**Issue by 2522001** [DO-NOTTO-DO/NotToDo-iOS#33]
## 🍏 Issue
* 상황 추가 뷰 UI를 추가 구현합니다.

## 📝 To-do

- [x] cell 클릭할 때 색상 변경하기
- [x] 텍스트 필드에 내용 있을 때 테두리 색상 변경하기
- [x] 최근 사용한 키워드 비었을 때 처리하기
- [x] 텍스트 필드 footerView로 처리하기
