### ISSUE TITLE
[FEAT] 생성 뷰 화면 전환 구현

### ISSUE THREAD

**Issue by 2522001** [DO-NOTTO-DO/NotToDo-iOS#46]
## 🍏 Issue
생성 뷰 화면 전환을 구현합니다.

## 📝 To-do

- [x] 생성 → 홈 dismiss
- [x] 생성 → 추천받기 push
- [x] 생성 → 상황 추가하기 push
- [ ] 생성 → 날짜 present
- [x] 생성 → 홈 push
